### ISSUE TITLE
Get snaps up and running

### ISSUE THREAD

**Issue by daPhipz** [bit101/version#22]
As a follow-up on #15, maybe we could discuss the actual implementation of snap support here. I will keep the following To-Do list up to date with the latest changes. If you notice that something is missing, please mention it in a comment.

----

### Before merging into `master`

- [ ] Solve the issue described in #21
- [ ] Make the version number change automatically in `snapcraft.yaml`
- [ ] Set up GitHub Actions to trigger a snap build whenever someone creates a PR to or pushes to `snap`
- [ ] Write tests that execute the snap inside the testing environment to make sure it runs flawlessly
- [ ] Merge into `master`

### After merging into `master`

- [ ] Change trigger in all related Github Actions (CI,CD)
- [ ] @bit101 (if you want to be the maintainer of the snap) sets up a `snapcraft.io` account and registers the snap there
- [ ] Set up an automatic build pipeline that triggers whenever a tag is pushed to `master` and sends a successfully built snap to the store

**Comment by daPhipz** [comment]
Alan Pope did a very beginner-friendly [video](https://www.youtube.com/watch?v=BEp_l2oUcD8) on how to create snaps some time ago - really worth a watch!

**Comment by bit101** [comment]
looks like you started doing the PRs to the snap branch but then switched over to master. I noticed the last one and reverted it, but didn't notice the others until after that. May need some cleanup.

**Comment by daPhipz** [comment]
Oh shoot! You are right. Will file the correct PRs in a second.

**Comment by bit101** [comment]
I plan to look into the snap stuff over the weekend. Very interested.

**Comment by daPhipz** [comment]
Nice! I have been trying to find a solution to #21 for a bit now, but maybe you are luckier than me ;)

**Comment by daPhipz** [comment]
https://snapcraft.io/docs/snapcraft-yaml-reference
https://snapcraft.io/docs/snapcraft-advanced-grammar

**Comment by bit101** [comment]
I spent some time today looking into this. Ran into the same issue with `version` not being able to see most tools. It does see some, but misses a lot. I think it's because snaps do not have access to the entire system. I made a snap that simply lists the contents of a path you pass in. While it can see `/usr/bin`, it cannot see `/usr/local/bin`, which is where many user programs are installed. In fact, the `/usr/bin` the snap sees has a different timestamp and entirely different contents than the actual `/usr/bin` on my system - only a small fraction of the files, and all different timestamps. So it is seeing some kind of internal overlay to the real filesystem.

Might be able to get around this with some interface, but essentially, `version` would need permissions to run any and all executable programs in the user's path. I think that's completely antithetical to the snap confinement model.

Feel free to bang away on it, but I'm thinking it's not going to work. But it was great to learn more about snaps. Now I want to make one that actually works!

**Comment by daPhipz** [comment]
Yeah, that was my issue as well. It doesn't even work with `classic` confinement, I think...
I'm glad it was a fun experience for you, though!
I unfortunately will not be able to contribute in the next few days, but I'll have a look at what needs to be done then!
